volumes:
  mysql-volume:

services:
  db:
    image: mysql:5
    platform: linux/x86_64
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample.password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "--user", "sample", "-psample.password" ]
      interval: 2s
      timeout: 1s
      retries: 30

  web: &web
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    ports:
      - "${DJANGO_LOCAL_PORT:-8000}:8000"
    environment:
      IN_DOCKER: dev
      DJANGO_SETTINGS_MODULE: webapp.settings
      DJANGO_DEBUG: 'true'

      DB_NAME: sample
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: sample
      DB_PASSWORD: sample.password

      REDIS_URL: redis://redis:6379

    # Make interactive
    stdin_open: true
    tty: true
    command: ["runserver", "0.0.0.0:8000"]

  pycharm:
    <<: *web
    entrypoint: [ ]
    command: ["echo", "Use the Run/Debug Configuration in PyCharm/IDEA"]
    ports:
      - "${LOCAL_PYCHARM_PORT:-8000}:8000"